default_context:
  author: Your Catacrocker CONFIG Name
  email: catacrockers_config@gmail.com
  project_name_full: Catacrocker Project CONFIG Name
  project_name: "{{ cookiecutter.project_name_full.lower().replace(' ', '_') }}"
  project_short_description: Refreshingly simple CONFIG Catacrocker project folder generator
  add_hello_world: 'yes'
  version: '0.5'
